# -*- coding: utf-8 -*-
"""Tugas 1 Kelompok 4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Uu-GnhRm4RqVWodBA4-u7n5XtlNXuN3M

1. Data Kotor
"""

data_kotor = " #001-wahyu aji-informatika-python,java,php-aktif "

"""2. PROSES PEMBERSIHAN (MANIPULASI STRING)

a. Menghapus spasi di ujung dan karakter '#' di awal (strip & replace).
"""

data_a = data_kotor.strip().replace('#', '')
print(data_a)

"""b. Memecah string menjadi list berdasarkan tanda pemisah '-' (split)."""

data_kotor = " #001-wahyu aji-informatika-python,java,php-aktif "
data_bersih = data_kotor.strip().replace("#", "")
hasil_split = data_bersih.split("_")

print(hasil_split)

"""c. Mengolah daftar skill/hobi (split & join)."""

data_list_lengkap= data_a.split('-')
skill_mentah=data_list_lengkap[3]
list_skill=skill_mentah.split(',')
skill_final="&".join(list_skill)

print(f"Skill Dikuasai:{skill_final}")

"""d. Menghitung panjang ID dan jumlah skill (len & count).

"""

panjang_id = len(id_mahasiswa)
total_skill = skill.count(",") + 1

print(f"Panjang ID: {panjang_id}")
print(f"Total Skill: {total_skill}")

"""3. OUTPUT AKHIR (Menggunakan F-String & Escape Character).

"""

data_kotor = " #001-wahyu aji-informatika-python,java,php-aktif "

print('=================================')
print('HASIL VERIFIKASI DATA')
print('=================================')

id_mahasiswa = '001'
nama = 'wahyu aji'
prodi = 'informatika'
skill = ['python', 'java', 'php']
total_skill = 3
status = 'aktif'

print(f"ID Mahasiswa: {id_mahasiswa}")
print(f"Nama: {nama}")
print(f"Prodi: {prodi}")
print(f"Skill: {skill}")
print(f"Total Skill: {total_skill}")
print(f"Status: {status}")

print ('=================================')