# -*- coding: utf-8 -*-
"""UTS KEL 4 (2411012021_Youngky Setiawan).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DTp0Dwk8OBHb2Al8O0hDMrw1CkQ2ugZZ
"""

raw_log = "ID:001#NAMA:kopi susu gula aren#QTY:3#PRICE:18000;ID:002#NAMA:COFFEE LATTE#QTY:1#PRICE:25000"

list_transaksi = raw_log.split(";")
transaksi_1 = list_transaksi[0]
transaksi_2 = list_transaksi[1]
atribut_t1 = transaksi_1.split("#")
atribut_t2 = transaksi_2.split("#")

nama_1 = atribut_t1[1].replace("NAMA:", "").strip().title()
qty_1 = int(atribut_t1[2].replace("QTY:", "").strip())
harga_1 = int(atribut_t1[3].replace("PRICE:", "").strip())

nama_2 = atribut_t2[1].replace("NAMA:", "").strip().title()
qty_2 = int(atribut_t2[2].replace("QTY:", "").strip())
harga_2 = int(atribut_t2[3].replace("PRICE:", "").strip())

subtotal_1 = qty_1 * harga_1
subtotal_2 = qty_2 * harga_2
total_pendapatan = subtotal_1 + subtotal_2

print("=======================================================")
print(f"{'LAPORAN HARIAN KEDAI SOU SPACE':^55}")
print("=======================================================")
print(f"{'MENU':<25} {'QTY':<5} {'HARGA':<10} {'SUBTOTAL'}")
print("-------------------------------------------------------")
print(f"{nama_1:<25} {qty_1:<5} {harga_1:<10} {subtotal_1}")
print(f"{nama_2:<25} {qty_2:<5} {harga_2:<10} {subtotal_2}")
print("-------------------------------------------------------")
print(f"{'TOTAL PENDAPATAN HARI INI:':<25} Rp {total_pendapatan}")
print("=======================================================")

"""*PENJELASAN PROGRAM*
*Double Splitting untuk Organisasi Data*
Jadi di sini kami mulai dari `raw_log`, yang isinya masih satu baris panjang dan semua data transaksi masih nyampur jadi satu. Supaya bisa diproses, kami pecah dulu pakai `.split(";")` biar tiap transaksi jadi terpisah.

Setelah itu, ternyata tiap transaksi masih gabungan juga (ada ID, nama, qty, harga), jadi kita pecah lagi pakai `.split("#")`. Dari situ baru bisa ambil satu per satu datanya, misalnya nama menu, jumlah, dan harga, pakai indexing.

*Cleaning Data (Menghapus Label yang Tidak Perlu)*
Nah, datanya masih ada tulisan kayak `"NAMA:"`, `"QTY:"`, dan `"PRICE:"`, jadi kami hapus dulu pakai `.replace()` biar yang tersisa cuma nilainya aja. Terus aku tambahin `.strip()` juga buat jaga-jaga kalau ada spasi yang nggak kepake.

*Standardisasi Format Nama*
Untuk nama menu, kami pakai `.title()` supaya tampilannya lebih rapi, jadi huruf awal tiap kata kapital dan enak dilihat.

*Casting ke Tipe Data Numerik*
Terus karena data jumlah dan harga itu awalnya masih string, kami ubah dulu ke angka pakai `int()`. Soalnya kalau nggak diubah, nanti nggak bisa dipakai buat hitung-hitungan.

*Perhitungan Aritmatika*
Kalau datanya sudah siap semua, baru kami hitung subtotal tiap menu (QTY X PRICE), lalu dijumlahin lagi buat dapetin total pendapatan hari itu. Soalnya kalau masih string, perkalian malah jadi ngulang teks, bukan hitung angka.

*Formatting Output dengan F-String*
Terakhir, kami tampilin hasilnya pakai f-string biar lebih rapi. Sekalian kita atur juga jaraknya supaya bentuknya kayak tabel dan gampang dibaca.
"""